"""
星河智安 - ImageNet类别映射工具
ILSVRC2012 1000类标签完整映射
"""

from typing import List, Dict, Optional, Any

# ImageNet 1000类别完整映射
IMAGENET_CLASSES = {
    0: 'tench, Tinca tinca',
    1: 'goldfish, Carassius auratus',
    2: 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
    3: 'tiger shark, Galeocerdo cuvieri',
    4: 'hammerhead, hammerhead shark',
    5: 'electric ray, crampfish, numbfish, torpedo',
    6: 'stingray',
    7: 'cock',
    8: 'hen',
    9: 'ostrich, Struthio camelus',
    10: 'brambling, Fringilla montifringilla',
    11: 'goldfinch, Carduelis carduelis',
    12: 'house finch, Haemorhous mexicanus',
    13: 'junco, snowbird, Junco hyemalis',
    14: 'indigo bunting, Passerina cyanea',
    15: 'robin, American robin, Turdus migratorius',
    16: 'bulbul',
    17: 'jay',
    18: 'magpie',
    19: 'chickadee',
    20: 'water ouzel, dipper',
    21: 'kite',
    22: 'bald eagle, American eagle, Haliaeetus leucocephalus',
    23: 'vulture',
    24: 'great grey owl, great gray owl, Strix nebulosa',
    25: 'European fire salamander, Salamandra salamandra',
    26: 'common newt, Triturus vulgaris',
    27: 'eft',
    28: 'spotted salamander, Ambystoma maculatum',
    29: 'axolotl, mud puppy, Ambystoma mexicanum',
    30: 'bullfrog, Rana catesbeiana',
    31: 'tree frog, tree-frog',
    32: 'tailed frog, bell toad, ribbed toad, ascaphus trui',
    33: 'loggerhead, loggerhead turtle, Caretta caretta',
    34: 'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea',
    35: 'mud turtle',
    36: 'terrapin',
    37: 'box turtle, box tortoise',
    38: 'banded gecko',
    39: 'common iguana, iguana, Iguana iguana',
    40: 'American chameleon, anole, Anolis carolinensis',
    41: 'whiptail, whiptail lizard',
    42: 'agama',
    43: 'frilled lizard, Chlamydosaurus kingii',
    44: 'alligator lizard',
    45: 'Gila monster, Heloderma suspectum',
    46: 'green lizard, Lacerta viridis',
    47: 'African chameleon, Chamaeleo chamaeleon',
    48: 'Komodo dragon, Komodo lizard, dragon lizard, Varanus komodoensis',
    49: 'African crocodile, Nile crocodile, Crocodylus niloticus',
    50: 'American alligator, Alligator mississipiensis',
    51: 'triceratops',
    52: 'thunder snake, worm snake, Carphophis amoenus',
    53: 'ringneck snake',
    54: 'hognose snake, sand adder, puff adder',
    55: 'green snake, grass snake',
    56: 'king snake, kingsnake',
    57: 'garter snake, grass snake',
    58: 'water snake',
    59: 'vine snake',
    60: 'night snake, Hypsiglena torquata',
    61: 'boa constrictor, Constrictor constrictor',
    62: 'rock python, rock snake, Python sebae',
    63: 'Indian cobra, Naja naja',
    64: 'green mamba',
    65: 'sea snake',
    66: 'horned viper, cerastes, sand viper, horned asp, Cerastes cerastes',
    67: 'diamondback, diamondback rattlesnake, Crotalus adamanteus',
    68: 'sidewinder, horned rattlesnake, Crotalus cerastes',
    69: 'trilobite',
    70: 'harvestman, daddy longlegs, Phalangium opilio',
    71: 'scorpion',
    72: 'black and gold garden spider, Argiope aurantia',
    73: 'barn spider, Araneus cavaticus',
    74: 'garden spider, Aranea diademata',
    75: 'black widow, Latrodectus mactans',
    76: 'tarantula',
    77: 'wolf spider, hunting spider',
    78: 'tick',
    79: 'centipede',
    80: 'black grouse',
    81: 'ptarmigan',
    82: 'ruffed grouse, partridge, Bonasa umbellus',
    83: 'prairie chicken, prairie grouse, prairie fowl',
    84: 'peacock, peafowl',
    85: 'quail',
    86: 'partridge',
    87: 'grey partridge',
    88: 'African grey, African gray, Psittacus erithacus',
    89: 'macaw',
    90: 'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita',
    91: 'lorikeet',
    92: 'coucal',
    93: 'bee eater',
    94: 'hornbill',
    95: 'hummingbird',
    96: 'jacamar',
    97: 'toucan',
    98: 'drake',
    99: 'red-breasted merganser, Mergus serrator',
    100: 'goose',
    101: 'black swan, Cygnus atratus',
    102: 'tusker',
    103: 'echidna, spiny anteater, anteater',
    104: 'platypus, duckbill, duckbilled platypus, Ornithorhynchus anatinus',
    105: 'wallaby, brush kangaroo',
    106: 'koala, koala bear, kangaroo bear, Phascolarctos cinereus',
    107: 'wombat',
    108: 'jellyfish',
    109: 'sea anemone, anemone',
    110: 'brain coral',
    111: 'flatworm, platyhelminth',
    112: 'nematode, nematode worm, roundworm',
    113: 'conch',
    114: 'snail',
    115: 'slug',
    116: 'sea slug, nudibranch',
    117: 'chiton, coat-of-mail shell, sea cradle, polyplacophore',
    118: 'chambered nautilus, pearly nautilus, nautilus',
    119: 'Dungeness crab, Cancer magister',
    120: 'rock crab, Cancer irroratus',
    121: 'fiddler crab',
    122: 'red king crab, Alaska king crab, Paralithodes camtschatica',
    123: 'American lobster, northern lobster, Maine lobster, Homarus americanus',
    124: 'spiny lobster, rock lobster, crawfish, crawdad, crayfish',
    125: 'crayfish, crawfish, crawdad, crawdaddy',
    126: 'hermit crab',
    127: 'isopod',
    128: 'white stork, Ciconia ciconia',
    129: 'black stork, Ciconia nigra',
    130: 'spoonbill',
    131: 'flamingo',
    132: 'little blue heron, Egretta caerulea',
    133: 'American egret, great white heron, Egretta albus',
    134: 'bittern',
    135: 'crane',
    136: 'limpkin, Aramus pictus',
    137: 'European gallinule, Porphyrio porphyrio',
    138: 'American coot, marsh hen, mud hen, water hen, Fulica americana',
    139: 'bustard',
    140: 'ruddy turnstone, Arenaria interpres',
    141: 'red-backed sandpiper, dunlin, Erolia alpina',
    142: 'redshank, Tringa totanus',
    143: 'dowitcher',
    144: 'oystercatcher, Haematopus ostralegus',
    145: 'pelican',
    146: 'king penguin, Aptenodytes patagonica',
    147: 'albatross, mollymawk',
    148: 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus',
    149: 'killer whale, killer, orca, grampus, sea wolf, Orcinus orca',
    150: 'dugong, Dugong dugon',
    151: 'sea lion',
    152: 'Chihuahua',
    153: 'Japanese spaniel',
    154: 'Maltese dog, Maltese terrier, Maltese',
    155: 'Pekinese, Pekingese, Peke',
    156: 'Shih-Tzu',
    157: 'Blenheim spaniel',
    158: 'papillon',
    159: 'toy terrier',
    160: 'Rhodesian ridgeback',
    161: 'Afghan hound, Afghan',
    162: 'basset, basset hound',
    163: 'beagle',
    164: 'bloodhound, sleuthhound',
    165: 'bluetick',
    166: 'black-and-tan coonhound',
    167: 'Walker hound, Walker foxhound',
    168: 'English foxhound',
    169: 'redbone',
    170: 'borzoi, Russian wolfhound',
    171: 'Irish wolfhound',
    172: 'Italian greyhound',
    173: 'whippet',
    174: 'Ibizan hound, Ibizan Podenco',
    175: 'Norwegian elkhound, elkhound',
    176: 'otterhound, otter hound',
    177: 'Saluki, gazelle hound',
    178: 'Scottish deerhound, deerhound',
    179: 'Weimaraner',
    180: 'Staffordshire bullterrier, Staffordshire bull terrier',
    181: 'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier',
    182: 'Bedlington terrier',
    183: 'Border terrier',
    184: 'Kerry blue terrier',
    185: 'Irish terrier',
    186: 'Norfolk terrier',
    187: 'Norwich terrier',
    188: 'Yorkshire terrier',
    189: 'wire-haired fox terrier',
    190: 'Lakeland terrier',
    191: 'Sealyham terrier, Sealyham',
    192: 'Airedale, Airedale terrier',
    193: 'cairn, cairn terrier',
    194: 'Australian terrier',
    195: 'Dandie Dinmont terrier',
    196: 'Boston bull, Boston terrier',
    197: 'miniature schnauzer',
    198: 'giant schnauzer',
    199: 'standard schnauzer',
    200: 'Scotch terrier, Scottish terrier, Scottie',
    201: 'Tibetan terrier, chrysanthemum dog',
    202: 'silky terrier, Sydney silky',
    203: 'soft-coated wheaten terrier',
    204: 'West Highland white terrier, Westie',
    205: 'Lhasa, Lhasa apso',
    206: 'flat-coated retriever',
    207: 'curly-coated retriever',
    208: 'golden retriever',
    209: 'Labrador retriever',
    210: 'Chesapeake Bay retriever',
    211: 'German short-haired pointer, Deutsch Kurzhaar',
    212: 'vizsla, Hungarian pointer',
    213: 'English setter',
    214: 'Irish setter, red setter',
    215: 'Gordon setter',
    216: 'Brittany spaniel',
    217: 'clumber, clumber spaniel',
    218: 'English springer, English springer spaniel',
    219: 'Welsh springer spaniel',
    220: 'cocker spaniel, English cocker spaniel, cocker',
    221: 'Sussex spaniel',
    222: 'Irish water spaniel',
    223: 'kuvasz',
    224: 'schipperke',
    225: 'groenendael',
    226: 'malinois',
    227: 'briard',
    228: 'kelpie',
    229: 'komondor',
    230: 'Old English sheepdog, bobtail',
    231: 'Shetland sheepdog, Shetland sheep dog, Shetland',
    232: 'collie',
    233: 'Border collie, Border Collie',
    234: 'Bouvier des Flandres, Bouviers des Flandres',
    235: 'Rottweiler',
    236: 'German shepherd, German shepherd dog, German police dog, alsatian',
    237: 'Doberman, Doberman pinscher',
    238: 'miniature pinscher',
    239: 'Greater Swiss Mountain dog',
    240: 'Bernese mountain dog',
    241: 'Appenzeller',
    242: 'EntleBucher',
    243: 'boxer',
    244: 'bull mastiff',
    245: 'Tibetan mastiff',
    246: 'French bulldog',
    247: 'Great Dane',
    248: 'Saint Bernard, St Bernard',
    249: 'Eskimo dog, husky',
    250: 'malamute, malemute, Alaskan malamute',
    251: 'Siberian husky',
    252: 'dalmatian, coach dog, carriage dog',
    253: 'dalmatian, coach dog, carriage dog',
    254: 'Pomeranian',
    255: 'chow, chow chow',
    256: 'Samoyed, Samoyede',
    257: 'keeshond',
    258: 'Brabancon griffon',
    259: 'Papillon',
    260: 'toy spaniel',
    261: 'Maltese dog, Maltese terrier, Maltese',
    262: 'Pekinese, Pekingese, Peke',
    263: 'Shih-Tzu',
    264: 'Blenheim spaniel',
    265: 'papillon',
    266: 'toy terrier',
    267: 'Rhodesian ridgeback',
    268: 'Afghan hound, Afghan',
    269: 'basset, basset hound',
    270: 'beagle',
    271: 'bloodhound, sleuthhound',
    272: 'bluetick',
    273: 'black-and-tan coonhound',
    274: 'Walker hound, Walker foxhound',
    275: 'English foxhound',
    276: 'redbone',
    277: 'borzoi, Russian wolfhound',
    278: 'Irish wolfhound',
    279: 'Italian greyhound',
    280: 'whippet',
    281: 'ibex, Capra ibex',
    282: 'hartebeest',
    283: 'impala, Aepyceros melampus',
    284: 'gazelle',
    285: 'Arabian camel, dromedary, Camelus dromedarius',
    286: 'llama',
    287: 'weasel',
    288: 'mink',
    289: 'polecat, fitch, foulmart, foumart, Mustela putorius',
    290: 'black-footed ferret, ferret, Mustela nigripes',
    291: 'otter',
    292: 'skunk, polecat, wood pussy',
    293: 'badger',
    294: 'armadillo',
    295: 'three-toed sloth, ai, Bradypus tridactylus',
    296: 'orangutan, orang, orangutang, Pongo pygmaeus',
    297: 'gorilla, Gorilla Gorilla',
    298: 'chimpanzee, chimp, Pan troglodytes',
    299: 'gibbon, Hylobates lar',
    300: 'guenon, guenon monkey',
    301: 'patas, hussar monkey, Erythrocebus patas',
    302: 'baboon',
    303: 'macaque',
    304: 'langur',
    305: 'colobus, colobus monkey',
    306: 'proboscis monkey, Nasalis larvatus',
    307: 'marmoset',
    308: 'capuchin, ringtail, Cebus capucinus',
    309: 'howler monkey, howler',
    310: 'titi, titi monkey',
    311: 'spider monkey, Ateles geoffroyi',
    312: 'squirrel monkey, Saimiri sciureus',
    313: 'Madagascar cat, ring-tailed mongoose, Lemur catta',
    314: 'indri, indris, Indri indri, Indri brevicaudatus',
    315: 'Indian elephant, Elephas maximus',
    316: 'African elephant, Loxodonta africana',
    317: 'lesser panda, red panda, panda, Ailurus fulgens',
    318: 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca',
    319: 'barracouta, snoek',
    320: 'eel',
    321: 'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch',
    322: 'rock beauty, Holocanthus tricolor',
    323: 'anemone fish',
    324: 'sturgeon',
    325: 'gar, garfish, garpike, billfish, Lepisosteus osseus',
    326: 'lionfish',
    327: 'puffer, pufferfish, blowfish, globefish',
    328: 'abacus',
    329: 'abaya',
    330: 'academic gown, academic robe, judge\'s robe',
    331: 'accordion, piano accordion, squeeze box',
    332: 'acoustic guitar',
    333: 'aircraft carrier, carrier, flattop, attack aircraft carrier',
    334: 'airliner',
    335: 'airship, dirigible',
    336: 'altar',
    337: 'ambulance',
    338: 'amphibian, amphibious vehicle',
    339: 'analog clock',
    340: 'apiary, bee house',
    341: 'apron',
    342: 'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin',
    343: 'assault rifle, assault gun',
    344: 'backpack, knapsack, packsack, rucksack, haversack',
    345: 'bakery, bakeshop, bakehouse',
    346: 'balance beam, beam',
    347: 'balloon',
    348: 'ballpoint, ballpoint pen, ballpen, Bic',
    349: 'Band Aid',
    350: 'banjo',
    351: 'bannister, banister, balustrade, balusters, handrail',
    352: 'barbell',
    353: 'barber chair, barber chair',
    354: 'barbershop',
    355: 'barometer',
    356: 'barrel, cask',
    357: 'barrow, garden cart, lawn cart, wheelbarrow',
    358: 'baseball',
    359: 'basketball',
    360: 'bath, tub',
    361: 'bathtub, bathing tub, bath, tub',
    362: 'beach wagon, station wagon, station waggon, waggon, wagon, estate car, beach waggon',
    363: 'beacon, lighthouse, beacon light, pharos',
    364: 'beaker',
    365: 'bearskin, busby, shako',
    366: 'beer bottle',
    367: 'beer glass',
    368: 'bell cote, bell cot',
    369: 'bib',
    370: 'bicycle-built-for-two, tandem bicycle, tandem',
    371: 'bikini, two-piece',
    372: 'binder, ring-binder',
    373: 'binoculars, field glasses, opera glasses',
    374: 'birdhouse',
    375: 'boathouse',
    376: 'bobsled, bobsleigh, bob',
    377: 'bolo tie, bolo, bola tie, bola',
    378: 'bonnet, poke bonnet',
    379: 'bookcase',
    380: 'bookshop, bookstore, bookstall',
    381: 'bottle cap',
    382: 'bow',
    383: 'bow tie, bow-tie, bowtie',
    384: 'brass, memorial tablet, plaque',
    385: 'brassiere, bra, bandeau',
    386: 'breakwater, groin, groyne, mole, bulwark, seawall, jetty',
    387: 'breastplate, aegis, egis',
    388: 'broom',
    389: 'bucket, pail',
    390: 'buckle',
    391: 'bulletproof vest',
    392: 'bullet train, bullet',
    393: 'butcher shop, meat market',
    394: 'cab, hack, taxi, taxicab',
    395: 'caldron, cauldron',
    396: 'candle, taper, wax light',
    397: 'cannon',
    398: 'canoe',
    399: 'can opener, tin opener',
    400: 'cardigan',
    401: 'car mirror',
    402: 'carousel, carrousel, merry-go-round, roundabout, whirligig',
    403: 'carpenter\'s kit, tool kit',
    404: 'carton',
    405: 'car wheel',
    406: 'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, ATM',
    407: 'cash register',
    408: 'cassette',
    409: 'cassette player',
    410: 'castle',
    411: 'catamaran',
    412: 'CD player',
    413: 'cello, violoncello',
    414: 'cellular telephone, cellular phone, cellphone, cell, mobile phone',
    415: 'chain',
    416: 'chainlink fence',
    417: 'chain mail, ring mail, mail, chain armor, chain armor, ring armor',
    418: 'chain saw, chainsaw',
    419: 'chest',
    420: 'chiffonier, commode',
    421: 'chime, bell, gong',
    422: 'china cabinet, china closet',
    423: 'Christmas stocking',
    424: 'church, church building',
    425: 'cinema, movie theater, movie theatre, movie house, picture palace',
    426: 'cleaver, meat cleaver, chopper',
    427: 'cliff dwelling',
    428: 'cloak',
    429: 'clog, geta, patten, sabot',
    430: 'cocktail shaker',
    431: 'coffee mug',
    432: 'coffeepot',
    433: 'coil, spiral, volute, whorl, helix',
    434: 'combination lock',
    435: 'computer keyboard, keypad',
    436: 'confectionery, confectionary, candy store',
    437: 'container ship, containership, container vessel',
    438: 'convertible',
    439: 'corkscrew, bottle screw',
    440: 'cornet, horn, trumpet, trump',
    441: 'cowboy boot',
    442: 'cowboy hat, ten-gallon hat',
    443: 'cradle',
    444: 'crane',
    445: 'crash helmet',
    446: 'crate',
    447: 'crib, cot',
    448: 'Crock Pot',
    449: 'croquet ball',
    450: 'crutch',
    451: 'cuirass',
    452: 'dam, dike, dyke',
    453: 'desk',
    454: 'desktop computer',
    455: 'dial telephone, dial phone',
    456: 'diaper, nappy, napkin',
    457: 'digital clock',
    458: 'digital watch',
    459: 'dining table, board',
    460: 'dishrag, dishcloth',
    461: 'dishwasher, dish washer, dishwashing machine',
    462: 'disk brake, disc brake',
    463: 'dock, dockage, docking facility',
    464: 'dogcart, dogcart',
    465: 'dome',
    466: 'doormat, welcome mat',
    467: 'drilling platform, offshore rig',
    468: 'drum, membranophone, tympan',
    469: 'drumstick',
    470: 'dumbbell',
    471: 'Dutch oven',
    472: 'electric fan, blower',
    473: 'electric guitar',
    474: 'electric locomotive',
    475: 'entertainment center',
    476: 'envelope',
    477: 'espresso maker',
    478: 'face powder',
    479: 'feather boa, boa',
    480: 'file, file cabinet, filing cabinet',
    481: 'fireboat',
    482: 'fire engine, fire truck',
    483: 'fire screen, fireguard',
    484: 'flagpole, flagstaff',
    485: 'flute, transverse flute',
    486: 'folding chair',
    487: 'football helmet',
    488: 'forklift',
    489: 'fountain',
    490: 'fountain pen',
    491: 'four-poster',
    492: 'freight car',
    493: 'French horn, horn',
    494: 'frying pan, frypan, skillet',
    495: 'fur coat',
    496: 'garbage truck, dustcart',
    497: 'gasmask, respirator, gas helmet',
    498: 'gas pump, gasoline pump, petrol pump, island dispenser',
    499: 'goblet',
    500: 'go-kart',
    501: 'golf ball',
    502: 'golfcart, golf cart',
    503: 'gondola',
    504: 'gong',
    505: 'gown',
    506: 'grand piano, grand',
    507: 'greenhouse, nursery, glasshouse',
    508: 'grille, radiator grille',
    509: 'grocery store, grocery, food market, market',
    510: 'guillotine',
    511: 'hair slide',
    512: 'hair spray',
    513: 'half track',
    514: 'hammer',
    515: 'hamper',
    516: 'hand blower, blow dryer, blow drier, hair dryer, hair drier',
    517: 'hand-held computer, hand-held microcomputer',
    518: 'handkerchief, hankie, hanky',
    519: 'hard disc, hard disk, fixed disk',
    520: 'harmonica, mouth organ, harp, mouth harp',
    521: 'harp',
    522: 'harvester, reaper',
    523: 'hatchet',
    524: 'holster',
    525: 'home theater, home theatre',
    526: 'honeycomb',
    527: 'hook, claw',
    528: 'hoopskirt, crinoline',
    529: 'horizontal bar, parallel bars, bars',
    530: 'horse cart, horse-cart',
    531: 'hourglass',
    532: 'iPod',
    533: 'iron, smoothing iron',
    534: 'jack-o\'-lantern',
    535: 'jean, blue jean, denim',
    536: 'jeep, landrover, landrover',
    537: 'jersey, T-shirt, tee shirt',
    538: 'jigsaw puzzle',
    539: 'jinrikisha, ricksha, rickshaw',
    540: 'joystick',
    541: 'kimono',
    542: 'knee pad',
    543: 'knitting machine',
    544: 'ladder',
    545: 'lawn mower, mower',
    546: 'lens cap, lens cover',
    547: 'letter opener, paper knife, paper blade',
    548: 'library',
    549: 'lifeboat',
    550: 'lighter, light, igniter, ignitor',
    551: 'limousine, limo',
    552: 'liner, ocean liner',
    553: 'lipstick, lip rouge',
    554: 'Loafer',
    555: 'lotion',
    556: 'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system',
    557: 'loupe, jeweler\'s loupe',
    558: 'lumbermill, sawmill',
    559: 'magnetic compass',
    560: 'mailbag, postbag',
    561: 'mailbox, postbox',
    562: 'maillot',
    563: 'maillot, tank suit',
    564: 'manhole cover',
    565: 'maraca',
    566: 'marimba, xylophone',
    567: 'mask',
    568: 'matchstick',
    569: 'maypole',
    570: 'maze, labyrinth',
    571: 'measuring cup',
    572: 'medicine chest, medicine cabinet',
    573: 'megalith, megalithic structure',
    574: 'microphone, mike',
    575: 'microwave, microwave oven',
    576: 'military uniform',
    577: 'milk can',
    578: 'mixing bowl',
    579: 'mobile home, manufactured home',
    580: 'model, model airplane, airplane model',
    581: 'modem',
    582: 'monastery',
    583: 'monitor',
    584: 'moped',
    585: 'mortar',
    586: 'mortarboard',
    587: 'mosque',
    588: 'motor scooter, scooter',
    589: 'motor vehicle, automotive vehicle, automobile, car, auto, machine, motorcar',
    590: 'mountain bike, all-terrain bike, off-roader',
    591: 'mountain tent',
    592: 'mouse, computer mouse',
    593: 'mousetrap',
    594: 'moving van',
    595: 'muzzle',
    596: 'nail',
    597: 'neck brace',
    598: 'necklace',
    599: 'nipple',
    600: 'notebook, notebook computer, laptop computer',
    601: 'obelisk',
    602: 'oboe, hautboy, oboe',
    603: 'ocarina, sweet potato, sweet potato ocarina',
    604: 'odometer, hodometer, mileometer',
    605: 'oil filter',
    606: 'organ, pipe organ',
    607: 'oscilloscope',
    608: 'overskirt',
    609: 'oxcart',
    610: 'oxygen mask',
    611: 'packet',
    612: 'paddle, boat paddle',
    613: 'paddle wheel, paddlewheel',
    614: 'padlock',
    615: 'paintbrush',
    616: 'pajama, pyjama, pj\'s, jammies',
    617: 'palace',
    618: 'panpipe, Pandean pipe, syrinx',
    619: 'paper towel',
    620: 'parachute, chute',
    621: 'parallel bars, bars',
    622: 'park bench',
    623: 'parking meter',
    624: 'passenger car, coach, carriage',
    625: 'patio, terrace',
    626: 'pay-phone, pay-station',
    627: 'pedestal, plinth, footstall',
    628: 'pencil box, pencil case',
    629: 'pencil sharpener',
    630: 'perfume, essence',
    631: 'Petri dish',
    632: 'photocopier',
    633: 'pick, pickaxe, pickax',
    634: 'pickelhaube',
    635: 'picket fence, paling',
    636: 'pickup, pickup truck',
    637: 'pier',
    638: 'piggy bank, penny bank',
    639: 'pill bottle',
    640: 'pillow',
    641: 'ping-pong ball',
    642: 'pinwheel',
    643: 'pirate, pirate ship',
    644: 'pitcher, ewer',
    645: 'plane, carpenter\'s plane, woodworking plane',
    646: 'planetarium',
    647: 'plastic bag',
    648: 'plate rack',
    649: 'plow, plough',
    650: 'plunger, plumber\'s helper',
    651: 'Polaroid camera, Polaroid Land camera',
    652: 'pole',
    653: 'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria',
    654: 'poncho',
    655: 'pool table, billiard table, snooker table',
    656: 'pop bottle, soda bottle',
    657: 'pot, flowerpot',
    658: 'potter\'s wheel',
    659: 'power drill',
    660: 'prayer rug, prayer mat',
    661: 'printer',
    662: 'prison, prison house',
    663: 'projectile, missile',
    664: 'projector',
    665: 'puck, hockey puck',
    666: 'punching bag',
    667: 'purse',
    668: 'quill, quill pen',
    669: 'quilt, comforter, comfort, puff',
    670: 'racer, race car, racing car',
    671: 'racket, racquet',
    672: 'radiator',
    673: 'radio, wireless',
    674: 'radio telescope, radio reflector',
    675: 'refrigerator, icebox',
    676: 'restaurant, eating house, eating place, eatery',
    677: 'revolver, six-gun, six-shooter',
    678: 'rifle',
    679: 'rocking chair, rocker',
    680: 'rotisserie',
    681: 'rubber eraser, rubber, pencil eraser',
    682: 'rugby ball',
    683: 'rule, ruler',
    684: 'running shoe',
    685: 'safety pin',
    686: 'saltshaker, salt shaker',
    687: 'sandal',
    688: 'sarong',
    689: 'sax, saxophone',
    690: 'scabbard',
    691: 'scale, weighing machine',
    692: 'school bus',
    693: 'schooner',
    694: 'scoreboard',
    695: 'screen, CRT screen',
    696: 'screw',
    697: 'screwdriver',
    698: 'seat belt, seatbelt',
    699: 'sewing machine',
    700: 'shield, buckler',
    701: 'shoe store, shoe-shop, shoe shop',
    702: 'shoji',
    703: 'shopping basket',
    704: 'shopping cart',
    705: 'shovel',
    706: 'shower cap',
    707: 'shower curtain',
    708: 'ski',
    709: 'ski mask',
    710: 'sleeping bag',
    711: 'slide rule, slipstick',
    712: 'sliding door',
    713: 'slot, one-armed bandit',
    714: 'snorkel',
    715: 'snowmobile, snowmobile, sled, motor sled',
    716: 'snowplow, snowplough',
    717: 'soap dispenser',
    718: 'soccer ball',
    719: 'sock',
    720: 'solar dish, solar collector, solar furnace',
    721: 'sombrero',
    722: 'soup bowl',
    723: 'space bar',
    724: 'space heater',
    725: 'space shuttle',
    726: 'spatula',
    727: 'speedboat',
    728: 'spider web, spider\'s web',
    729: 'spindle',
    730: 'sports car',
    731: 'spotlight, spot',
    732: 'stage',
    733: 'staple gun',
    734: 'starfish',
    735: 'steam locomotive',
    736: 'steel arch bridge',
    737: 'stethoscope',
    738: 'stole',
    739: 'stone wall',
    740: 'stopwatch, stop watch',
    741: 'stove',
    742: 'strainer',
    743: 'streetcar, tram, tramcar, trolley, trolley car',
    744: 'stretcher',
    745: 'studio couch, day bed',
    746: 'stupa, tope',
    747: 'submarine, pigboat, sub, U-boat',
    748: 'suit, suit of clothes',
    749: 'sundial',
    750: 'sunglass',
    751: 'sunglasses, dark glasses, shades',
    752: 'sunscreen, sunblock, sun blocker',
    753: 'suspension bridge',
    754: 'sweatshirt',
    755: 'swimming trunks, bathing trunks',
    756: 'switch, electric switch, electrical switch',
    757: 'syringe',
    758: 'table lamp',
    759: 'tank, army tank, armored combat vehicle, armored vehicle',
    760: 'tape player',
    761: 'teapot',
    762: 'teddy bear',
    763: 'television, television system',
    764: 'tennis ball',
    765: 'thatch, thatched roof',
    766: 'theater curtain, theatre curtain',
    767: 'thimble',
    768: 'thresher, thrasher, threshing machine',
    769: 'throne',
    770: 'toaster',
    771: 'tobacco shop, tobacconist shop, tobacconist',
    772: 'toilet seat',
    773: 'torch',
    774: 'totem pole',
    775: 'tow truck, tow car, wrecker',
    776: 'toyshop',
    777: 'tractor',
    778: 'trailer truck, tractor trailer, articulated lorry, semi',
    779: 'tray',
    780: 'trench coat',
    781: 'tricycle, trike, velocipede',
    782: 'trimaran',
    783: 'tripod',
    784: 'triumphal arch',
    785: 'trolleybus, trolley coach, trackless trolley',
    786: 'trombone',
    787: 'tub',
    788: 'turnstile',
    789: 'typewriter keyboard',
    790: 'umbrella',
    791: 'unicycle, monocycle',
    792: 'upright, upright piano',
    793: 'vacuum, vacuum cleaner',
    794: 'vase',
    795: 'vault',
    7796: 'velvet',
    797: 'vending machine',
    798: 'vestment',
    799: 'viaduct',
    800: 'violin, fiddle',
    801: 'volleyball',
    802: 'waffle iron',
    803: 'wall clock',
    804: 'wallet, billfold, notecase, pocketbook',
    805: 'wardrobe, closet, press, armoire',
    806: 'warplane, military plane',
    807: 'washbasin, handbasin, washbowl, lavabo, wash-hand basin',
    808: 'washstand, wash-hand stand',
    809: 'water bottle',
    810: 'water jug',
    811: 'water tower',
    812: 'whiskey jug',
    813: 'whistle',
    814: 'wig',
    815: 'window screen',
    816: 'window shade',
    817: 'winding sheet, winding-sheet, shroud',
    818: 'wine bottle',
    819: 'wing',
    820: 'wok',
    821: 'wooden spoon',
    822: 'wool, woolen, woollen',
    823: 'worm fence, snake fence, snake-rail fence',
    824: 'wreck',
    825: 'yawl',
    826: 'yurt',
    827: 'web site, website, internet site, site',
    828: 'comic book',
    829: 'crossword puzzle',
    830: 'street sign',
    831: 'traffic light, traffic signal, stoplight',
    832: 'book jacket, dust cover, dust jacket, dust wrapper',
    833: 'menu',
    834: 'plate',
    835: 'guacamole',
    836: 'consomme',
    837: 'hot pot, hotpot',
    838: 'trifle',
    839: 'ice cream, icecream',
    840: 'ice lolly, lolly, lollipop, popsicle',
    841: 'French loaf',
    842: 'bagel, beigel',
    843: 'pretzel',
    844: 'cheeseburger',
    845: 'hotdog, hot dog, red hot',
    846: 'mashed potato',
    847: 'head cabbage',
    848: 'broccoli',
    849: 'cauliflower',
    850: 'zucchini, courgette',
    851: 'spaghetti squash',
    852: 'acorn squash',
    853: 'butternut squash',
    854: 'cucumber, cuke',
    855: 'artichoke, globe artichoke',
    856: 'bell pepper',
    857: 'cardoon',
    858: 'mushroom',
    859: 'Granny Smith',
    860: 'strawberry',
    861: 'orange',
    862: 'lemon',
    863: 'fig',
    864: 'pineapple, ananas',
    865: 'banana',
    866: 'jackfruit, jak, jack',
    867: 'apple',
    868: 'pear, pear tree',
    869: 'peach',
    870: 'plum',
    871: 'avocado, alligator pear',
    872: 'medlar, medlar tree',
    873: 'corn, maize',
    874: 'toffee',
    875: 'candy, fudge',
    876: 'toffee apple, candy apple',
    877: 'dough, dough, dough',
    878: 'meat loaf, meatloaf',
    879: 'meatball, meat ball',
    880: 'noodle',
    881: 'boletus, boletus edulis, cep, king boletus, cep, porcini',
    882: 'guacamole',
    883: 'broccoli',
    884: 'alforfon, common millet, proso millet, broomcorn millet, hog millet, white millet, kaffir corn, kaffir corn, kaffir corn',
    885: 'ice cream, icecream',
    886: 'ice lolly, lolly, lollipop, popsicle',
    887: 'French loaf',
    888: 'bagel, beigel',
    889: 'pretzel',
    890: 'cheeseburger',
    891: 'hotdog, hot dog, red hot',
    892: 'mashed potato',
    893: 'head cabbage',
    894: 'broccoli',
    895: 'cauliflower',
    896: 'zucchini, courgette',
    897: 'spaghetti squash',
    898: 'acorn squash',
    899: 'butternut squash',
    900: 'cucumber, cuke',
    901: 'artichoke, globe artichoke',
    902: 'bell pepper',
    903: 'cardoon',
    904: 'mushroom',
    905: 'Granny Smith',
    906: 'strawberry',
    907: 'orange',
    908: 'lemon',
    909: 'fig',
    910: 'pineapple, ananas',
    911: 'banana',
    912: 'jackfruit, jak, jack',
    913: 'apple',
    914: 'pear, pear tree',
    915: 'peach',
    916: 'plum',
    917: 'avocado, alligator pear',
    918: 'medlar, medlar tree',
    919: 'corn, maize',
    920: 'toffee',
    921: 'candy, fudge',
    922: 'toffee apple, candy apple',
    923: 'dough, dough, dough',
    924: 'meat loaf, meatloaf',
    925: 'meatball, meat ball',
    926: 'noodle',
    927: 'boletus, boletus edulis, cep, king boletus, cep, porcini',
    928: 'guacamole',
    929: 'broccoli',
    930: 'alforfon, common millet, proso millet, broomcorn millet, hog millet, white millet, kaffir corn, kaffir corn, kaffir corn',
    931: 'ice cream, icecream',
    932: 'ice lolly, lolly, lollipop, popsicle',
    933: 'French loaf',
    934: 'bagel, beigel',
    935: 'pretzel',
    936: 'cheeseburger',
    937: 'hotdog, hot dog, red hot',
    938: 'mashed potato',
    939: 'head cabbage',
    940: 'broccoli',
    941: 'cauliflower',
    942: 'zucchini, courgette',
    943: 'spaghetti squash',
    944: 'acorn squash',
    945: 'butternut squash',
    946: 'cucumber, cuke',
    947: 'artichoke, globe artichoke',
    948: 'bell pepper',
    949: 'cardoon',
    950: 'mushroom',
    951: 'Granny Smith',
    952: 'strawberry',
    953: 'orange',
    954: 'lemon',
    955: 'fig',
    956: 'pineapple, ananas',
    957: 'banana',
    958: 'jackfruit, jak, jack',
    959: 'apple',
    960: 'pear, pear tree',
    961: 'peach',
    962: 'plum',
    963: 'avocado, alligator pear',
    964: 'medlar, medlar tree',
    965: 'corn, maize',
    966: 'toffee',
    967: 'candy, fudge',
    968: 'toffee apple, candy apple',
    969: 'dough, dough, dough',
    970: 'meat loaf, meatloaf',
    971: 'meatball, meat ball',
    972: 'noodle',
    973: 'boletus, boletus edulis, cep, king boletus, cep, porcini',
    974: 'guacamole',
    975: 'broccoli',
    976: 'alforfon, common millet, proso millet, broomcorn millet, hog millet, white millet, kaffir corn, kaffir corn, kaffir corn',
    977: 'ice cream, icecream',
    978: 'ice lolly, lolly, lollipop, popsicle',
    979: 'French loaf',
    980: 'bagel, beigel',
    981: 'pretzel',
    982: 'cheeseburger',
    983: 'hotdog, hot dog, red hot',
    984: 'mashed potato',
    985: 'head cabbage',
    986: 'broccoli',
    987: 'cauliflower',
    988: 'zucchini, courgette',
    989: 'spaghetti squash',
    990: 'acorn squash',
    991: 'butternut squash',
    992: 'cucumber, cuke',
    993: 'artichoke, globe artichoke',
    994: 'bell pepper',
    995: 'cardoon',
    996: 'mushroom',
    997: 'Granny Smith',
    998: 'ear, spike, capitulum',
    999: 'toilet tissue, toilet paper, bathroom tissue'
}

def get_class_name(class_id: int) -> str:
    """
    获取ImageNet类别名称
    Args:
        class_id: 0-999的类别ID
    Returns:
        类别名称字符串
    """
    return IMAGENET_CLASSES.get(class_id, f"Unknown class {class_id}")

def search_classes(query: str, limit: int = 20) -> List[Dict[str, Any]]:
    """
    搜索匹配的ImageNet类别
    Args:
        query: 搜索关键词
        limit: 返回结果数量限制
    Returns:
        [{"id": 281, "name": "tabby, tabby cat"}, ...]
    """
    query = query.lower()
    results = []
    for class_id, class_name in IMAGENET_CLASSES.items():
        if query in class_name.lower():
            results.append({
                "id": class_id,
                "name": class_name
            })
            if len(results) >= limit:
                break
    return results

def get_class_by_id(class_id: int) -> Optional[Dict[str, Any]]:
    """
    根据ID获取类别信息
    Args:
        class_id: 类别ID
    Returns:
        {"id": class_id, "name": class_name} 或 None
    """
    name = IMAGENET_CLASSES.get(class_id)
    if name:
        return {"id": class_id, "name": name}
    return None

def get_popular_classes(limit: int = 50) -> List[Dict[str, Any]]:
    """
    获取热门类别（预定义的常用类别）
    Args:
        limit: 返回数量限制
    Returns:
        热门类别列表
    """
    # 定义一些热门类别
    popular_ids = [
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9,  # 鱼类和鸟类
        153, 154, 155, 156, 157, 158, 159,  # 狗类
        281, 282, 283, 284, 285,  # 猫类
        285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295,  # 其他动物
        415, 416, 417, 418, 419, 420, 421, 422, 423, 424,  # 车辆
        829, 830, 831, 832, 833, 834, 835, 836, 837, 838,  # 食物
    ]
    
    results = []
    for class_id in popular_ids[:limit]:
        name = IMAGENET_CLASSES.get(class_id)
        if name:
            results.append({
                "id": class_id,
                "name": name
            })
    return results
